# Generated by Django 5.1.13 on 2026-03-13 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("title", models.CharField(max_length=255)),
                ("authors", models.CharField(max_length=500)),
                (
                    "publication_date",
                    models.CharField(
                        blank=True,
                        help_text="Format: YYYY or YYYY-MM or YYYY-MM-DD",
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter date in YYYY or YYYY-MM or YYYY-MM-DD format.",
                                regex="^(\\d{4}|\\d{4}-\\d{2}|\\d{4}-\\d{2}-\\d{2})$",
                            )
                        ],
                    ),
                ),
                (
                    "pages",
                    models.CharField(
                        blank=True, help_text="e.g., 10-18", max_length=50, null=True
                    ),
                ),
                ("isbn", models.CharField(blank=True, max_length=50, null=True)),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Digital Object Identifier (DOI)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "formatting_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON field to store rich text formatting (bold, italic, underline) for title, authors, publisher",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("title", models.CharField(max_length=255)),
                ("authors", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "publication_date",
                    models.CharField(
                        blank=True,
                        help_text="Format: YYYY or YYYY-MM or YYYY-MM-DD",
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter date in YYYY or YYYY-MM or YYYY-MM-DD format.",
                                regex="^(\\d{4}|\\d{4}-\\d{2}|\\d{4}-\\d{2}-\\d{2})$",
                            )
                        ],
                    ),
                ),
                ("conference_name", models.CharField(max_length=255)),
                ("venue", models.CharField(blank=True, max_length=255, null=True)),
                ("isbn", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "pages",
                    models.CharField(
                        blank=True, help_text="e.g., 10-18", max_length=50, null=True
                    ),
                ),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Digital Object Identifier (DOI)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "formatting_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON field to store rich text formatting (bold, italic, underline) for title, authors, conference_name, publisher",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "originators",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "publication_date",
                    models.CharField(
                        blank=True,
                        help_text="Format: YYYY or YYYY-MM or YYYY-MM-DD",
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter date in YYYY or YYYY-MM or YYYY-MM-DD format.",
                                regex="^(\\d{4}|\\d{4}-\\d{2}|\\d{4}-\\d{2}-\\d{2})$",
                            )
                        ],
                    ),
                ),
                (
                    "under_publication",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Separate with commas",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="datasets/"),
                ),
                (
                    "formatting_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON field to store rich text formatting (bold, italic, underline) for title, originators",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "service_key",
                    models.CharField(
                        default="mlflow",
                        help_text="Logical service identifier, e.g. 'mlflow', 'matflow', 'eda'",
                        max_length=50,
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers shown first)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "ordering": ["order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="HeaderSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "service_key",
                    models.CharField(
                        default="mlflow",
                        help_text="Logical service identifier, e.g. 'mlflow', 'matflow', 'eda'",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "title_image",
                    models.FileField(blank=True, null=True, upload_to="header_images/"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HeroImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "service_key",
                    models.CharField(
                        default="mlflow",
                        help_text="Logical service identifier, e.g. 'mlflow', 'matflow', 'eda'",
                        max_length=50,
                    ),
                ),
                ("hero_image", models.ImageField(upload_to="header_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("title", models.CharField(max_length=255)),
                ("authors", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "publication_date",
                    models.CharField(
                        blank=True,
                        help_text="Format: YYYY or YYYY-MM or YYYY-MM-DD",
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter date in YYYY or YYYY-MM or YYYY-MM-DD format.",
                                regex="^(\\d{4}|\\d{4}-\\d{2}|\\d{4}-\\d{2}-\\d{2})$",
                            )
                        ],
                    ),
                ),
                ("journal_name", models.CharField(max_length=255)),
                ("volume", models.CharField(blank=True, max_length=50, null=True)),
                ("issue", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "pages",
                    models.CharField(
                        blank=True, help_text="e.g., 10-18", max_length=50, null=True
                    ),
                ),
                ("issn", models.CharField(blank=True, max_length=30, null=True)),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Digital Object Identifier (DOI)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "formatting_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON field to store rich text formatting (bold, italic, underline) for title, authors, journal_name, publisher, volume",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OurServiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "service_key",
                    models.CharField(
                        default="mlflow",
                        help_text="Logical service identifier, e.g. 'mlflow', 'matflow', 'eda'",
                        max_length=50,
                    ),
                ),
                (
                    "service_logo",
                    models.ImageField(
                        blank=True, default="", upload_to="service_logos/"
                    ),
                ),
                ("service_name", models.CharField(max_length=255)),
                ("service_description", models.TextField()),
                ("service_url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Patent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("title", models.CharField(max_length=255)),
                ("inventors", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "publication_date",
                    models.CharField(
                        blank=True,
                        help_text="Format: YYYY or YYYY-MM or YYYY-MM-DD",
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter date in YYYY or YYYY-MM or YYYY-MM-DD format.",
                                regex="^(\\d{4}|\\d{4}-\\d{2}|\\d{4}-\\d{2}-\\d{2})$",
                            )
                        ],
                    ),
                ),
                (
                    "patent_office",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "patent_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "application_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "patent_link",
                    models.URLField(
                        blank=True,
                        help_text="Link to patent (e.g., Google Patents or USPTO)",
                        null=True,
                    ),
                ),
                (
                    "formatting_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON field to store rich text formatting (bold, italic, underline) for title, inventors",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "visitor_id",
                    models.CharField(
                        help_text="Cookie/localStorage-based unique visitor ID",
                        max_length=64,
                    ),
                ),
                (
                    "visitor_type",
                    models.CharField(
                        choices=[("guest", "Guest"), ("user", "User")],
                        default="guest",
                        max_length=10,
                    ),
                ),
                ("visited_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SupportLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "service_key",
                    models.CharField(
                        default="mlflow",
                        help_text="Logical service identifier, e.g. 'mlflow', 'matflow', 'eda'",
                        max_length=50,
                    ),
                ),
                ("support_logo", models.ImageField(upload_to="support_logos/")),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers shown first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "ordering": ["order", "-id"],
            },
        ),
    ]
