# Generated by Django 5.1.13 on 2025-11-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_source', models.CharField(choices=[('book', 'Book'), ('journal', 'Journal Article'), ('website', 'Website'), ('report', 'Report'), ('thesis', 'Thesis / Dissertation'), ('other', 'Other')], default='book', max_length=20)),
                ('author', models.CharField(blank=True, help_text="Name of individual author(s), e.g., 'Smith, J. D.'", max_length=255)),
                ('corporate_author', models.CharField(blank=True, help_text="If corporate author, e.g., 'World Health Organization'", max_length=255)),
                ('title', models.CharField(max_length=300)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('journal_name', models.CharField(blank=True, max_length=200)),
                ('volume', models.CharField(blank=True, max_length=20)),
                ('issue', models.CharField(blank=True, max_length=20)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True)),
                ('access_date', models.DateField(blank=True, null=True)),
                ('tag_name', models.CharField(blank=True, help_text='Optional short tag for reference management.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Citation',
                'verbose_name_plural': 'Citations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
