# Generated by Django 5.1.13 on 2025-11-19 13:23

from django.db import migrations, models
from django.utils import timezone


def set_created_at_for_existing_records(apps, schema_editor):
    """Set created_at to current time for existing records"""
    HeroImage = apps.get_model('common', 'HeroImage')
    SupportLogo = apps.get_model('common', 'SupportLogo')
    
    now = timezone.now()
    HeroImage.objects.filter(created_at__isnull=True).update(created_at=now)
    SupportLogo.objects.filter(created_at__isnull=True).update(created_at=now)


def reverse_set_created_at(apps, schema_editor):
    """Reverse migration - set created_at to None"""
    HeroImage = apps.get_model('common', 'HeroImage')
    SupportLogo = apps.get_model('common', 'SupportLogo')
    
    HeroImage.objects.all().update(created_at=None)
    SupportLogo.objects.all().update(created_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_headersection_heroimage_ourserviece_supportlogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='supportlogo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, blank=True),
        ),
        migrations.RunPython(set_created_at_for_existing_records, reverse_set_created_at),
    ]
