# Generated by Django 5.1.13 on 2025-11-19 13:25

from django.db import migrations
from django.utils import timezone


def set_created_at_for_existing_records(apps, schema_editor):
    """Set created_at to current time for existing records that have null created_at"""
    HeroImage = apps.get_model('common', 'HeroImage')
    SupportLogo = apps.get_model('common', 'SupportLogo')
    
    now = timezone.now()
    HeroImage.objects.filter(created_at__isnull=True).update(created_at=now)
    SupportLogo.objects.filter(created_at__isnull=True).update(created_at=now)


def reverse_set_created_at(apps, schema_editor):
    """Reverse migration - set created_at to None for records that were updated"""
    # This is a no-op for reverse migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_add_created_at_to_heroimage_supportlogo'),
    ]

    operations = [
        migrations.RunPython(set_created_at_for_existing_records, reverse_set_created_at),
    ]
