# Generated by Django 5.1.13 on 2025-11-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_update_existing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='view_link',
            field=models.URLField(blank=True, help_text='Link to view the conference paper', null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='pages',
            field=models.CharField(blank=True, help_text='e.g., 10-18', max_length=50, null=True),
        ),
    ]
