# Generated by Django 5.1.13 on 2025-11-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_conference_view_link_alter_conference_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='doi',
            field=models.CharField(blank=True, help_text='Digital Object Identifier (DOI)', max_length=255, null=True),
        ),
    ]
