# Generated by Django 5.1.13 on 2025-11-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_journal_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='pages',
            field=models.CharField(blank=True, help_text='e.g., 10-18', max_length=50, null=True),
        ),
    ]
