# Generated by Django 5.1.13 on 2025-11-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_journal_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='view_link',
        ),
        migrations.AddField(
            model_name='conference',
            name='doi',
            field=models.CharField(blank=True, help_text='Digital Object Identifier (DOI)', max_length=255, null=True),
        ),
    ]
