# Generated by Django 5.1.13 on 2025-11-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_remove_conference_view_link_conference_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='doi',
            field=models.CharField(blank=True, help_text='Digital Object Identifier (DOI)', max_length=255, null=True),
        ),
    ]
