# Generated by Django 5.1.13 on 2025-11-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_book_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='patent_link',
            field=models.URLField(blank=True, help_text='Link to patent (e.g., Google Patents or USPTO)', null=True),
        ),
    ]
