# Generated by Django 5.1.13 on 2025-11-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_patent_patent_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='formatting_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='JSON field to store rich text formatting (bold, italic, underline) for title, authors, publisher', null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='formatting_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='JSON field to store rich text formatting (bold, italic, underline) for title, authors, conference_name, publisher', null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='formatting_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='JSON field to store rich text formatting (bold, italic, underline) for title, originators', null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='formatting_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='JSON field to store rich text formatting (bold, italic, underline) for title, authors, journal_name, publisher, volume', null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='formatting_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='JSON field to store rich text formatting (bold, italic, underline) for title, inventors', null=True),
        ),
    ]
