# Generated by Django 5.1.13 on 2025-12-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_book_formatting_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersection',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='header_images/'),
        ),
    ]
