# Generated by Django 5.1.13 on 2026-01-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_add_title_image_to_headersection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headersection',
            name='title_image',
            field=models.FileField(blank=True, null=True, upload_to='header_images/'),
        ),
    ]
