# Generated by Django 5.1.13 on 2026-01-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_headersection_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersection',
            name='service_key',
            field=models.CharField(default='mlflow', help_text="Logical service identifier, e.g. 'mlflow', 'matflow', 'eda'", max_length=50),
        ),
        migrations.AddField(
            model_name='heroimage',
            name='service_key',
            field=models.CharField(default='mlflow', help_text="Logical service identifier, e.g. 'mlflow', 'matflow', 'eda'", max_length=50),
        ),
        migrations.AddField(
            model_name='ourserviece',
            name='service_key',
            field=models.CharField(default='mlflow', help_text="Logical service identifier, e.g. 'mlflow', 'matflow', 'eda'", max_length=50),
        ),
        migrations.AddField(
            model_name='supportlogo',
            name='service_key',
            field=models.CharField(default='mlflow', help_text="Logical service identifier, e.g. 'mlflow', 'matflow', 'eda'", max_length=50),
        ),
    ]
