# Generated by Django 5.1.13 on 2026-02-12 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_headersection_service_key_heroimage_service_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.CharField(blank=True, help_text='Format: YYYY or YYYY-MM or YYYY-MM-DD', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter date in YYYY or YYYY-MM or YYYY-MM-DD format.', regex='^(\\d{4}|\\d{4}-\\d{2}|\\d{4}-\\d{2}-\\d{2})$')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='authors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='publication_date',
            field=models.CharField(blank=True, help_text='Format: YYYY or YYYY-MM or YYYY-MM-DD', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter date in YYYY or YYYY-MM or YYYY-MM-DD format.', regex='^(\\d{4}|\\d{4}-\\d{2}|\\d{4}-\\d{2}-\\d{2})$')]),
        ),
        migrations.AlterField(
            model_name='conference',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='keywords',
            field=models.CharField(blank=True, help_text='Separate with commas', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='originators',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='publication_date',
            field=models.CharField(blank=True, help_text='Format: YYYY or YYYY-MM or YYYY-MM-DD', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter date in YYYY or YYYY-MM or YYYY-MM-DD format.', regex='^(\\d{4}|\\d{4}-\\d{2}|\\d{4}-\\d{2}-\\d{2})$')]),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='under_publication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='authors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='publication_date',
            field=models.CharField(blank=True, help_text='Format: YYYY or YYYY-MM or YYYY-MM-DD', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter date in YYYY or YYYY-MM or YYYY-MM-DD format.', regex='^(\\d{4}|\\d{4}-\\d{2}|\\d{4}-\\d{2}-\\d{2})$')]),
        ),
        migrations.AlterField(
            model_name='journal',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='application_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='inventors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='patent_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='patent_office',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='publication_date',
            field=models.CharField(blank=True, help_text='Format: YYYY or YYYY-MM or YYYY-MM-DD', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter date in YYYY or YYYY-MM or YYYY-MM-DD format.', regex='^(\\d{4}|\\d{4}-\\d{2}|\\d{4}-\\d{2}-\\d{2})$')]),
        ),
    ]
