# Generated by Django 5.1.13 on 2026-02-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_relax_article_required_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('service_key', models.CharField(default='mlflow', help_text="Logical service identifier, e.g. 'mlflow', 'matflow', 'eda'", max_length=50)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers shown first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
