# Generated by Django 5.1.13 on 2026-02-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_add_faq_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(help_text='Cookie/localStorage-based unique visitor ID', max_length=64)),
                ('visitor_type', models.CharField(choices=[('guest', 'Guest'), ('user', 'User')], default='guest', max_length=10)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['visited_at'], name='common_site_visited_89bb71_idx')],
            },
        ),
    ]
