# Generated by Django 5.1.13 on 2026-02-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_add_sitevisit_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourserviece',
            name='service_logo',
            field=models.ImageField(blank=True, default='', upload_to='service_logos/'),
        ),
    ]
