# Generated by Django 5.1.13 on 2026-02-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_alter_ourserviece_service_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportlogo',
            options={'ordering': ['order', '-id']},
        ),
        migrations.AddField(
            model_name='supportlogo',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers shown first)'),
        ),
    ]
