# Generated by Django 5.1.13 on 2025-12-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='slug',
        ),
    ]
