from django.urls import path
from . import views
from .views import *
from .views import deploy_batch_cancel, deploy_batch_status

urlpatterns = [
    path('display_group/', display_group, name='display-api'),
    path('display_correlation/', display_correlation, name='display-api'),
    path('display_correlation_featurePair/', display_correlation_featurePair, name='display-api'),
    path('display_correlation_heatmap/', display_correlation_heatmap, name='display_correlation_heatmap'),
    path('change_dtype/', changeDtype, name='Change_dtype'),
    path('alter_field_name/', Alter_field, name='alter_field'),
    path('merge_dataset/', merge_dataset, name='merge_dataset'),
    path('encoding/', Encoding, name='encoding'),
    path('scaling/', Scaling, name='scaling'),
    path('drop_column/', Drop_column, name='dropping'),
    path('drop_rows/', Drop_row, name='dropping'),
    path('append/', Append, name='dropping'),
    path('imputation_data1', imputation_data1, name='imputation_data1'),
    path('imputation_data2', imputation_data2, name='imputation_data2'),
    path('imputation_result', imputation_result, name='imputation_result'),
    path('feature_selection/', feature_selection_api, name='dropping'),
    path('cluster/', Cluster, name='dropping'),
    path('split_dataset/', Split, name='dropping'),
    path('dataset_metadata/', DatasetMetadata, name='dataset_metadata'),
    path('build_model/', Build_model, name='dropping'),
    path('time_series/', Time_series, name='dropping'),
    path('time_series_analysis/', Time_series_analysis, name='dropping'),
    path('hyperparameter_optimization/', Hyper_opti, name='dropping'),
    path('model_evaluation/', model_evaluation, name='dropping'),
    path('model_prediction/', model_prediction, name='dropping'),
    path('download_model/', download_model, name='download_model'),
    path('reverseml/', Reverse_ml, name='dropping'),
    path('deploy_data/', deploy_data, name="deploy_data"),
    path('deploy_result/', deploy_result, name="deploy_result"),
    path('deploy_batch/', deploy_batch, name="deploy_batch"),
    path('deploy_batch_status/<str:task_id>/', deploy_batch_status, name="deploy_batch_status"),
    path('deploy_batch_cancel/<str:task_id>/', deploy_batch_cancel, name="deploy_batch_cancel"),
    path('feature_creation/', feature_creation, name="feature_creation"),
]
